import { useCallback, useRef, useState } from 'react';
import { Printer, FileDown, Image, Share2, Smartphone, Mail, Loader2, CheckCircle, AlertCircle, X } from 'lucide-react';
import type { RefObject } from 'react';

export type DocumentType = 'invoice' | 'quotation' | 'delivery-note';
interface ExportPanelProps { isOpen: boolean; onClose: () => void; documentType: DocumentType; documentNumber: string; documentLabel: string; customerName: string; customerPhone?: string; customerWhatsapp?: string; customerEmail?: string; businessName: string; exportRootRef: RefObject<HTMLElement | null>; onPrint: () => void; widthMm?: number; }

export default function ExportPanel({ isOpen, onClose, documentNumber, documentLabel, customerName, customerPhone, customerWhatsapp, customerEmail, businessName, exportRootRef, onPrint, widthMm = 190 }: ExportPanelProps) {
  const [status, setStatus] = useState<{ type: 'idle' | 'generating' | 'success' | 'failed'; text: string }>({ type: 'idle', text: '' });
  const [active, setActive] = useState<string | null>(null);
  const cache = useRef<{ name: string; blob: Blob } | null>(null);
  const [nativeAvailable, setNativeAvailable] = useState(() => typeof navigator !== 'undefined' && Boolean(navigator.share && navigator.canShare));
  const fileName = `${documentLabel.replace(/[^a-z0-9_-]+/gi, '_')}_${documentNumber.replace(/[^a-z0-9_-]+/gi, '_')}.pdf`;
  const setMessage = (type: typeof status.type, text: string, action: string | null = null) => { setStatus({ type, text }); setActive(action); };
  const download = useCallback((blob: Blob, name: string) => { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }, []);
  const exportRoot = () => { const root = exportRootRef.current; if (!root || !root.matches('[data-export-root="true"]')) throw new Error('Document is not ready'); return root; };
  const getFile = async () => {
    const blob = cache.current?.name === fileName ? cache.current.blob : await (await import('../../services/exportService')).createPdfBlobFromElement(exportRoot(), widthMm);
    if (!blob?.size) throw new Error('PDF could not be generated');
    cache.current = { name: fileName, blob };
    return new File([blob], fileName, { type: 'application/pdf' });
  };
  const run = async (name: string, work: () => Promise<void>) => { setMessage('generating', 'Preparing document...', name); try { await work(); } catch (error) { console.error(error); setMessage('failed', 'Could not prepare the document. Please try again.', name); } finally { setActive(null); } };
  const share = () => run('share', async () => {
    // The PDF work and navigator.share start from this click handler; no automatic download occurs.
    const file = await getFile();
    if (!navigator.share || !navigator.canShare || !navigator.canShare({ files: [file] })) { setNativeAvailable(false); setMessage('failed', 'File sharing is unavailable. Use the fallback options below.', 'share'); return; }
    try { await navigator.share({ title: `${documentLabel} ${documentNumber}`, text: `Please find the ${documentLabel} ${documentNumber} from ${businessName}.`, files: [file] }); setMessage('success', 'Document shared with the PDF attached.', 'share'); }
    catch (error) { if (error instanceof DOMException && error.name === 'AbortError') setMessage('idle', 'Sharing cancelled.'); else throw error; }
  });
  const pdf = () => run('pdf', async () => { const file = await getFile(); download(file, file.name); setMessage('success', 'PDF downloaded.', 'pdf'); });
  const image = () => run('image', async () => { await (await import('../../services/exportService')).exportInvoiceAsImage(exportRoot(), fileName.replace(/\.pdf$/, ''), widthMm); setMessage('success', 'Image downloaded.', 'image'); });
  const print = () => { setMessage('generating', 'Opening print dialog...', 'print'); onPrint(); setMessage('success', 'Print dialog opened.', 'print'); };
  const wa = () => run('whatsapp', async () => { const phone = customerWhatsapp || customerPhone; if (!phone) throw new Error('Missing WhatsApp number'); const file = await getFile(); download(file, file.name); const digits = phone.replace(/\D/g, ''); const number = digits.startsWith('91') ? digits : `91${digits.slice(-10)}`; window.open(`https://wa.me/${number}?text=${encodeURIComponent(`Please find the ${documentLabel} ${documentNumber} from ${businessName}.`)}`, '_blank', 'noopener,noreferrer'); setMessage('success', 'WhatsApp opened. Attach the downloaded PDF manually.', 'whatsapp'); });
  const email = () => run('email', async () => { if (!customerEmail) throw new Error('Missing customer email'); const file = await getFile(); download(file, file.name); const subject = encodeURIComponent(`${documentLabel} ${documentNumber} from ${businessName}`); const body = encodeURIComponent(`Dear ${customerName || 'Customer'},\n\nPlease find the ${documentLabel.toLowerCase()} ${documentNumber} from ${businessName}.\n\nThank you.`); window.location.href = `mailto:${customerEmail}?subject=${subject}&body=${body}`; setMessage('success', `Email draft opened for ${customerEmail}. Attach the downloaded PDF manually.`, 'email'); });
  if (!isOpen) return null;
  const actions = [ ...(nativeAvailable ? [{ id: 'share', label: 'Share Document', text: 'Share PDF attachment', icon: Share2, run: share, primary: true }] : []), { id: 'print', label: 'Print', text: 'Browser print dialog', icon: Printer, run: print }, { id: 'pdf', label: 'Download PDF', text: 'A4 PDF file', icon: FileDown, run: pdf }, { id: 'image', label: 'Download Image', text: 'PNG image', icon: Image, run: image }, ...(!nativeAvailable ? [{ id: 'whatsapp', label: 'Open WhatsApp', text: 'Attach PDF manually', icon: Smartphone, run: wa }] : []), { id: 'email', label: 'Open Email', text: 'Attach PDF manually', icon: Mail, run: email } ];
  const StatusIcon = status.type === 'generating' ? Loader2 : status.type === 'success' ? CheckCircle : AlertCircle;
  return <><div onClick={onClose} className="fixed inset-0 z-40 bg-black/30" /><div className="fixed inset-x-0 bottom-0 z-50 mx-auto max-w-lg rounded-t-3xl bg-white p-5 shadow-2xl pb-[calc(env(safe-area-inset-bottom)+1rem)]"><div className="mb-5 flex items-center justify-between"><div><h3 className="text-lg font-bold text-stone-800">Export & Share</h3><p className="text-xs text-stone-500">{documentLabel} #{documentNumber}</p></div><button onClick={onClose} className="inline-flex min-h-[48px] min-w-[48px] items-center justify-center rounded-xl text-stone-600 hover:bg-stone-100" aria-label="Close"><X /></button></div>{status.text && <div className={`mb-4 flex items-center gap-2 rounded-xl border p-3 text-sm ${status.type === 'failed' ? 'border-rose-200 bg-rose-50 text-rose-800' : status.type === 'success' ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-blue-200 bg-blue-50 text-blue-800'}`}><StatusIcon size={18} className={status.type === 'generating' ? 'animate-spin' : ''} />{status.text}</div>}<div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{actions.map((action) => { const Icon = action.icon; const loading = active === action.id; return <button key={action.id} onClick={action.run} disabled={Boolean(active)} className={`flex min-h-[56px] items-center gap-3 rounded-2xl border p-3 text-left font-semibold disabled:cursor-not-allowed disabled:opacity-50 ${action.primary ? 'sm:col-span-2 border-emerald-600 bg-emerald-600 text-white' : 'border-stone-200 bg-white text-stone-700 hover:border-emerald-300 hover:bg-emerald-50'}`}>{loading ? <Loader2 className="animate-spin" /> : <Icon size={22} />}<span>{action.label}</span><span className={`ml-auto text-[10px] font-normal ${action.primary ? 'text-emerald-50' : 'text-stone-500'}`}>{action.text}</span></button>; })}</div>{!nativeAvailable && <p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">Your browser cannot attach files to the share sheet. The PDF downloads first, then attach it manually in WhatsApp or email.</p>}</div></>;
}
